name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuración de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login a Docker Hub usando secretos
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Obtener versión del package.json
      - name: Get package.json version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 5️⃣ Obtener hash del commit y timestamp
      - name: Get commit hash and timestamp
        id: get_commit_info
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +"%d--%m-%YT%H-%M")
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      # 6️⃣ Construcción y push de la imagen con tag dinámico
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-react-app:${{ env.VERSION }}-${{ env.COMMIT_HASH }}-${{ env.TIMESTAMP }}

      # 7️⃣ Limpieza opcional
      - name: Docker system prune
        run: docker system prune -f
